[package]
edition = "2021"
name = "passkey"
version = "0.1.0"

[dependencies]
base64 = "0.22.1"
rand = "0.8.5"
ring = "0.17.8"
rusqlite = { version = "0.32.1", features = ["bundled"] }
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.134"
thiserror = "2.0.9"
